### PR TITLE
LoyaltyCards and FirstClass

### LINKED ISSUE #9: expose firstClass option
Please add "class" parameter to be able specify it during POST

### PR DESCRIPTION
**Pull request by Schmiddiii**
Should close https://github.com/derhuerst/db-rest/issues/9.

I have not written JS in a few years, that is why some code might be suboptimal. `routes/journeys.js` is mostly copied from [hafas-rest-api](https://github.com/public-transport/hafas-rest-api/blob/master/routes/journeys.js). I do not really know how to not copy everything, as the linked file does not export too much. This might need refactoring in the future.

### CODE REVIEW

**Comment by derhuerst** [comment]
Thanks for your contribution!

The JS you wrote is fine, and it works. 😉 But I decided to do two things differently:

> I do not really know how to not copy everything, as the linked file does not export too much. This might need refactoring in the future.

Indeed, I had to [add a hook function to `hafas-rest-api` that allows consuming projects to add their own query parameter parsers](https://github.com/public-transport/hafas-rest-api/commit/f4780c179ebde4f64ff80aca83a694bf80cc9945).

Also, instead of using the internal numeric codes for the different loyalty card types, I opted for (yet another) notation: `shcard`, `bahncard-1st-25`, etc. It is still confusing, but less so than random numeric codes.

What do you think about it?

**Comment by Schmiddiii** [comment]
> Indeed, I had to [add a hook function to hafas-rest-api that allows consuming projects to add their own query parameter parsers](https://github.com/public-transport/hafas-rest-api/commit/f4780c179ebde4f64ff80aca83a694bf80cc9945).

Looks way better than what I did.

> Also, instead of using the internal numeric codes for the different loyalty card types, I opted for (yet another) notation: shcard, bahncard-1st-25, etc. It is still confusing, but less so than random numeric codes.

Are these documented yet? The docs link to `https://github.com/public-transport/hafas-client/blob/68ecd7c5e976dd2f51c5c64a81600e7e181a8996/p/db/loyalty-cards.js#L6-L11` but these names do not exactly match.

**Comment by derhuerst** [comment]
> Are these documented yet? The docs link to `https://github.com/public-transport/hafas-client/blob/68ecd7c5e976dd2f51c5c64a81600e7e181a8996/p/db/loyalty-cards.js#L6-L11` but these names do not exactly match.

In the Open API playground, `loyaltyCard` shows up as a drop down menu.

In the ["manual" API docs](https://github.com/derhuerst/db-rest/blob/5/docs/api.md), the possible values don't show up yet, because [the generation logic doesn't handle enums yet](https://github.com/public-transport/hafas-rest-api/blob/60335eacd8332d7f448da875a7498dd97934e360/tools/generate-docs.js#L17-L36). (PR very welcome!)

**Comment by Schmiddiii** [comment]
I see, but the provided link in the manual does, in my opinion, not really make sense. Maybe link to https://github.com/derhuerst/db-rest/blob/25debd10b6bcfa9a95182099a24098bc8ed3fe36/lib/loyalty-cards.js#L6-L16 would make more sense? But both work fine by me, as long as I know them.

**Comment by derhuerst** [comment]
> I see, but the provided link in the manual does, in my opinion, not really make sense. Maybe link to […] [`db-rest/lib/loyalty-cards.js`].

Yes, that makes more sense, but this link would be self-referential, and would therefore always be outdated.

I think the best option is to remove the link and add all possible values to the documentation.

**Pull request closed without merging**
