### PR TITLE
Add travellers age parameter

### LINKED ISSUE #25: expose hafas-client's support for age-based tariffs
[`hafas-client@5.24.0` has added support for age-based tariffs with the DB profile](https://github.com/public-transport/hafas-client/blob/5.24.0/docs/changelog.md#5240), via https://github.com/public-transport/hafas-client/pull/264.

We should expose them here.

### LINKED ISSUE #29: allow customising the traveller's age (/journeys)
Hi, it would be great if you can add the travelers age to this endpoint: https://v6.db.transport.rest/api/journeys

### PR DESCRIPTION
**Pull request by JannesT3011**
This allows age-based tariffs.

fixes #29
fixes #25

### CODE REVIEW

**Review by derhuerst — COMMENTED** [review]
You also need to add it to `config.mapRouteParsers()`:

https://github.com/derhuerst/db-rest/blob/779e67886bbaf550d52ff6c6e826bd7a866cf851/api.js#L62

**Comment by JannesT3011** [comment]
I hope this is what you mean 😅

**Comment by derhuerst** [comment]
Sorry, I totally missed that you had already added it to `mapRouteParsers()`.

**Comment by derhuerst** [comment]
I have slightly amended your changes (`default: 'false'` -> `defaultStr: '*adult*'`).

**Comment by derhuerst** [comment]
Thanks!

**Pull request merged**
